### ISSUE TITLE
Updates needed

### ISSUE THREAD

**Issue by ravidreams** [tshrinivasan/tamil-wikipedia-word-list#1]
tawiki-latest-pages-articles.xml.tar.bz2

needs to be changed as

tawiki-latest-pages-articles.xml.bz2

according to the latest file formats we have at 

http://dumps.wikimedia.org/tawiki/latest/

Tar xvjf  tawiki-latest-pages-articles.xml.tar.bz2

command also need to be changed suitably to extract

---

python fine_tamil.py

should be corrected at

python find_tamil.py

**Comment by tshrinivasan** [comment]
Fixed this.
