### ISSUE TITLE
Unique words accuracy?

### ISSUE THREAD

**Issue by ravidreams** [tshrinivasan/tamil-wikipedia-word-list#2]
I ran this today and got 

1962477 final-tamil.txt

But the .txt file has lot of repeat words. Is this normal? I thought final-tamil.txt gives unique list of words.

**Comment by tshrinivasan** [comment]
Thanks for reporting.

Changed the process to find unique words.

Check now.

**Comment by ravidreams** [comment]
I ran again and got 1360126 unique words. It is different from 1197913 you show in readme. Did you get this count today?

Also, you have left the sort function now. Need it back.

**Comment by tshrinivasan** [comment]
My results are for the  dump on Jan 6.
Added sorting.
